[tool.mypy]
plugins = ["sqlalchemy.ext.mypy.plugin"]
strict = true
enable_error_code = [
  "redundant-expr",
  "truthy-bool",
  "ignore-without-code",
  "unused-awaitable",
  "type-arg",
  "redundant-cast",
  "comparison-overlap",
  "unreachable",
]

# Error Formatting
show_column_numbers = true
show_error_context = true
show_error_codes = true
show_traceback = true
pretty = true
color_output = true
error_summary = true
